"""empty message

Revision ID: 84df30ca5aea
Revises: 
Create Date: 2022-04-09 08:51:49.078119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84df30ca5aea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sender_mail', sa.VARCHAR(length=80), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), nullable=True),
    sa.Column('content', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
